# Generated by Django 2.2.6 on 2019-10-14 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('science', 'Science'), ('english', 'English')], max_length=50)),
                ('level', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year')], max_length=50)),
                ('topic', models.CharField(choices=[('fractions', 'Fractions'), ('algebra', 'Algebra'), ('vocabulary', 'Vocabulary')], max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_by', models.ManyToManyField(related_name='saved_resources', to='boardapp.TeacherModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='boardapp.TeacherModel')),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='boardapp.ResourceModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='boardapp.TeacherModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boardapp.ResourceModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_comments', to='boardapp.TeacherModel')),
            ],
        ),
    ]
