# Generated by Django 2.2.6 on 2019-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemodel',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_resources', to='boardapp.TeacherModel'),
        ),
    ]
