# Generated by Django 2.2.6 on 2019-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20191018_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=50),
        ),
    ]
