# Generated by Django 2.2.6 on 2019-10-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20191018_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=50, null=True),
        ),
    ]
