# Generated by Django 2.2.6 on 2019-10-14 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20191014_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
