# Generated by Django 2.2.6 on 2019-10-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20191018_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='boardapp.ProfileModel'),
        ),
    ]
