# Generated by Django 2.2.6 on 2019-10-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_auto_20191018_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemodel',
            old_name='teacher',
            new_name='author',
        ),
    ]
