# Generated by Django 2.2.6 on 2019-10-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20191018_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='rator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='boardapp.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='boardapp.ProfileModel'),
        ),
    ]
