# Generated by Django 2.2.6 on 2019-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_auto_20191015_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='_teachermodel_followed_by_+', to='boardapp.TeacherModel'),
        ),
    ]
