# Generated by Django 2.2.6 on 2019-10-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_auto_20191018_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_comments', to='boardapp.ProfileModel'),
        ),
    ]
