# Generated by Django 2.2.6 on 2019-10-18 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_auto_20191018_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemodel',
            name='saved_by',
            field=models.ManyToManyField(blank=True, default='', related_name='saved_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='followed_by',
            field=models.ManyToManyField(blank=True, default='', related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
