# Generated by Django 2.2.6 on 2019-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_auto_20191017_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
