# Generated by Django 2.2.6 on 2019-10-19 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_auto_20191018_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='rator',
            new_name='rated_by',
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
