# Generated by Django 2.2.6 on 2019-10-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_resourcemodel_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
