# Generated by Django 2.2.6 on 2019-10-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_remove_studentmodel_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsStudentAllowedtoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
