# Generated by Django 2.2.6 on 2019-10-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0014_isstudentallowedtopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcemodel',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='resourcemodel',
            name='note',
        ),
        migrations.AddField(
            model_name='levelmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardapp.SubjectModel'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('exercise', 'Exercise'), ('notes', 'Notes')], default='exercise', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardapp.LevelModel'),
        ),
        migrations.DeleteModel(
            name='ExerciseModel',
        ),
        migrations.DeleteModel(
            name='NoteModel',
        ),
    ]
