# Generated by Django 2.2.6 on 2019-10-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0016_auto_20191023_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_topics', to='boardapp.SubjectModel'),
        ),
    ]
